CREATE TYPE Poll.udtTeamStat AS TABLE
(
	TeamName VARCHAR(50) NOT NULL,
	StatType VARCHAR(50) NOT NULL,
	Season INT NOT NULL,
	[Week] INT NOT NULL,
	Games INT NOT NULL,
	Points DECIMAL(10,2),
	PassCompletions DECIMAL(10,2),
	PassAttempts DECIMAL(10,2),
	PassPercent DECIMAL(10,2),
	PassYards DECIMAL(10,2),
	PassTDs DECIMAL(10,2),
	RushAttempts DECIMAL(10,2),
	RushYards DECIMAL(10,2),
	RushAverage DECIMAL(10,2),
	RushTDs DECIMAL(10,2),
	TotalPlays DECIMAL(10,2),
	TotalYards DECIMAL(10,2),
	FirstDownsPass DECIMAL(10,2),
	FirstDownsRush DECIMAL(10,2),
	FirstDownsPenalty DECIMAL(10,2),
	FirstDownsTotal DECIMAL(10,2),
	PenaltiesNumber DECIMAL(10,2),
	PenaltiesYards DECIMAL(10,2),
	TurnoversFumble DECIMAL(10,2),
	TurnoversInterception DECIMAL(10,2),
	TurnoversTotal DECIMAL(10,2)
);