CREATE TABLE Poll.TeamStatistics
(
	ID INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	TeamVersionID INT NOT NULL,
	StatisticsTypeID INT NOT NULL,
	[Week] INT NOT NULL,
	Games INT NOT NULL,
	Points DECIMAL(10,2),
	PassCompletions DECIMAL(10,2),
	PassAttempts DECIMAL(10,2),
	PassPercent DECIMAL(10,2),
	PassYards DECIMAL(10,2),
	PassTDs DECIMAL(10,2),
	RushAttempts DECIMAL(10,2),
	RushYards DECIMAL(10,2),
	RushAverage DECIMAL(10,2),
	RushTDs DECIMAL(10,2),
	TotalPlays DECIMAL(10,2),
	TotalYards DECIMAL(10,2),
	FirstDownsPass DECIMAL(10,2),
	FirstDownsRush DECIMAL(10,2),
	FirstDownsPenalty DECIMAL(10,2),
	FirstDownsTotal DECIMAL(10,2),
	PenaltiesNumber DECIMAL(10,2),
	PenaltiesYards DECIMAL(10,2),
	TurnoversFumble DECIMAL(10,2),
	TurnoversInterception DECIMAL(10,2),
	TurnoversTotal DECIMAL(10,2)
	CONSTRAINT FK_TeamVersion_TeamVersion FOREIGN KEY (TeamVersionID) REFERENCES Poll.TeamVersion(ID),
	CONSTRAINT FK_TeamVersion_StatisticsType FOREIGN KEY (StatisticsTypeID) REFERENCES Poll.StatisticsType(ID),
	CONSTRAINT UC_TeamStatistics UNIQUE (TeamVersionID, StatisticsTypeID, [Week])
);