CREATE TABLE Poll.TeamVersion
(
	ID INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	TeamID INT NOT NULL,
	SeasonID INT NOT NULL,
	LeagueID INT NOT NULL,
	ConferenceID INT NOT NULL,
	DivisionID INT NULL,
	CONSTRAINT FK_TeamVersion_Team FOREIGN KEY (TeamID) REFERENCES Poll.Team(ID),
	CONSTRAINT FK_TeamVersion_Season FOREIGN KEY (SeasonID) REFERENCES Poll.Season(ID),
	CONSTRAINT FK_TeamVersion_League FOREIGN KEY (LeagueID) REFERENCES Poll.League(ID),
	CONSTRAINT FK_TeamVersion_Conference FOREIGN KEY (ConferenceID) REFERENCES Poll.Conference(ID),
	CONSTRAINT FK_TeamVersion_Division FOREIGN KEY (DivisionID) REFERENCES Poll.Division(ID)
);